---
title: "In-class Exercise 5"
author: "YSYK"
date: 11 Feb 2023
date-modified: "`r Sys.Date()`"
execute: 
  echo: true
  eval: true
  warning: false
format: html
editor: visual
---

## Install and launching R packages

```{r}
pacman::p_load(corrplot,ggstatsplot,tidyverse)
```

## Importing Data

```{r}
wine <- read_delim("data/wine_quality.csv")
```

## **Building a basic correlation matrix**

```{r}
pairs(wine[,1:11])
```

```{r}
pairs(wine[,2:12])
```

## **Drawing the lower corner**

```{r}
pairs(wine[,2:12], upper.panel = NULL)
```

```{r}
pairs(wine[,2:12], lower.panel = NULL)
```

## **The basic plot**

```{r}
ggstatsplot::ggcorrmat(data = wine, cor.vars = 1:11)
```

```{r}
ggstatsplot::ggcorrmat(
  data = wine, 
  cor.vars = 1:11,
  ggcorrplot.args = list(outline.color = "black", 
                         hc.order = TRUE,
                         tl.cex = 10),
  title    = "Correlogram for wine dataset",
  subtitle = "Four pairs are no significant at p < 0.05"
)
```

## **Getting started with corrplot**

```{r}
wine.cor <- cor(wine[,1:11],use="pairwise.complete.obs")
```

```{r}
corrplot(wine.cor)
```

```{r}
corrplot(wine.cor, method = "ellipse") 
```

## **Working with mixed layout**

```{r}
corrplot.mixed(wine.cor, 
               lower = "ellipse", 
               upper = "number",
               tl.pos = "lt",
               diag = "l",
               tl.col = "black")
```
