---
title: "In-class Exercise 4"
author: "YSYK"
date: 4 Feb 2023
date-modified: "`r Sys.Date()`"
execute: 
  echo: true
  eval: true
  warning: false
format: html
editor: visual
---


------------------------------------------------------------------------

title: "In-class Exercise 04" author: "YSYK" date: 4 Feb 2023 date-modified: "`r Sys.Date()`" execute: echo: true eval: true warning: false format: html editor: visual ---

## Install and launching R packages

```{r}
pacman::p_load(ggstatsplot,tidyverse,ggiraph,patchwork,plotly)
pacman::p_load(readxl, performance, parameters, see)
```

## 

Importing the data

```{r}
exam_data <- read_csv("data/Exam_data.csv")
car_resale <- read_xls("data/ToyotaCorolla.xls", "data")
```

## Visualization

### Working with visual variable: plot_ly() method

```{r}
plot_ly(data = exam_data, 
             x = ~MATHS, 
             y = ~ENGLISH,
             color = ~RACE,
             colors = "Set3")
```

### Creating an interactive scatter plot: ggplotly() method

```{r}
p <- ggplot(data=exam_data, 
            aes(x = MATHS,
                y = ENGLISH)) +
  geom_point(dotsize = 1) +
  coord_cartesian(xlim=c(0,100),
                  ylim=c(0,100))
ggplotly(p) #<<
```

```{r}
ggbetweenstats(
  data = exam_data,
  x = GENDER, 
  y = MATHS,
  type = "np",
  messages = FALSE
)
```

```{r}
model <- lm(Price ~ Age_08_04 + Mfg_Year + KM + 
              Weight + Guarantee_Period, data = car_resale)
model
```

```{r}
check_collinearity(model)
```

```{r}
check_c <- check_collinearity(model)
plot(check_c)
```

```{r}
model1 <- lm(Price ~ Age_08_04 + KM + 
              Weight + Guarantee_Period, data = car_resale)
check_n <- check_normality(model1)
plot(check_n)
```

```{r}
check_h <- check_heteroscedasticity(model1)
plot(check_h)
```

```{r}
check_model(model1)
```

```{r}
plot(parameters(model1))
```

```{r}
ggcoefstats(model1, 
            output = "plot")
```

```{r}
my_sum <- exam_data %>%
  group_by(RACE) %>%
  summarise(
    n=n(),
    mean=mean(MATHS),
    sd=sd(MATHS)
    ) %>%
  mutate(se=sd/sqrt(n-1))

knitr::kable(head(my_sum), format = 'html')

# Visualizing the uncertainty of point estimates: ggplot2 methods
ggplot(my_sum) +
  geom_errorbar(
    aes(x=RACE, 
        ymin=mean-se, 
        ymax=mean+se), 
    width=0.2, 
    colour="black", 
    alpha=0.9, 
    size=0.5) +
  geom_point(aes
           (x=RACE, 
            y=mean), 
           stat="identity", 
           color="red",
           size = 1.5,
           alpha=1) +
  ggtitle("Standard error of mean 
          maths score by rac")
```
